### ISSUE TITLE
Converting sparse IndexedSlices to a dense Tensor of unknown shape

### ISSUE THREAD

**Issue by GabrielLin** [fudannlp16/CWS_Dict#4]
I use Tensorflow 1.3.1. When I run train_dict.py. A warning has been shown:

> /opt/anaconda2/envs/tf1p3py27/lib/python2.7/site-packages/tensorflow/python/ops/gradients_impl.py:95: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
>   "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
> 

Do you have this situation?

**Comment by fudannlp16** [comment]
Yes, you can ignore it.

**Comment by GabrielLin** [comment]
OK.
