### ISSUE TITLE
dev_step() takes exactly 5 arguments (4 given)

### ISSUE THREAD

**Issue by GabrielLin** [fudannlp16/CWS_Dict#5]
When I run:
`python train_dict.py --dataset msr --model DictHyperModel --model_path mymsr`
After a long epoch info log, an error has been shown:

> ('epoch:0>>99.32%', 'completed in 959.34 (sec) <<\r')
> ('epoch:0>>99.48%', 'completed in 960.52 (sec) <<\r')
> ('epoch:0>>99.64%', 'completed in 961.96 (sec) <<\r')
> ('epoch:0>>99.81%', 'completed in 963.57 (sec) <<\r')
> Train Epoch 0 loss 14.632959
> Traceback (most recent call last):
>   File "train_dict.py", line 183, in <module>
>     train()
>   File "train_dict.py", line 104, in train
>     loss, predict= model.dev_step(sess, input_x, y)
> TypeError: dev_step() takes exactly 5 arguments (4 given)
> 

Thanks.

**Comment by fudannlp16** [comment]
Sorry, I have modified this error(train_dict.py).

**Comment by GabrielLin** [comment]
It works now. Thanks.
